hpmt_vars = ["design",
"flow_temp",
"HP_TYPE",
"capacity",
"estimated_annual_generation",
"scop",
"manufacturer",
"product_name",
"HP_INSTALLED",
"cost",
"HP_INSTALL_DATE",
"effective_to",
"effective_from",
"latitude",
"longitude",
"air_source_hp_certified",
"exhaust_air_hp_certified",
"ground_water_source_hp_certified",
"company_unique_id",
"company_name",
"BUILT_FORM",
"CONSTRUCTION_AGE_BAND",
"FLOOR_ENERGY_EFF",
"HOT_WATER_ENERGY_EFF",
"LIGHTING_ENERGY_EFF",
"MAINHEAT_ENERGY_EFF",
"ROOF_ENERGY_EFF",
"WALLS_ENERGY_EFF",
"WINDOWS_ENERGY_EFF",
"CURRENT_ENERGY_RATING",
"POTENTIAL_ENERGY_RATING",
"LATITUDE",
"LONGITUDE",
"COUNTRY",
"POSTCODE",
"GLAZED_AREA",
"GLAZED_TYPE",
"HEATING_FUEL",
"HEATING_SYSTEM",
"INSPECTION_DATE",
"MAINS_GAS_FLAG",
"MCS_AVAILABLE",
"EPC_AVAILABLE",
"NUMBER_HABITABLE_ROOMS",
"PHOTO_SUPPLY",
"SOLAR_WATER_HEATING_FLAG",
"TENURE",
"TOTAL_FLOOR_AREA",
"PROPERTY_TYPE",
"UPRN"]


most_mcs_columns = ['capacity',
       'estimated_annual_generation', 'installer_name', 'design', 'cost',
        'product_name', 'manufacturer','company_unique_id', 'company_name', 'latitude', 'longitude',
       'effective_from', 'effective_to', 'air_source_hp_certified',
       'ground_water_source_hp_certified', 'exhaust_air_hp_certified']